# Esse é um exemplo básico de Classificação: Score de créditos

A ideia é que o aluno tenha contato com um script que mostre alguns dos passos iniciais no machine learning.

**Suponha que você trabalha em um banco e possui uma base de dados de 100.000 clientes. E nos é dada a tarefa de criar uma classificação de score de créditos, baseados no histórico desses clientes.**

<br>

In [ ]:
# Bibliotecas

# Manipulação de dados
import pandas as pd

# Faz a conversão de text para number
from sklearn.preprocessing import LabelEncoder

# Nearest Neighbors (KNN) > Vizinhos Proximos
from sklearn.neighbors import KNeighborsClassifier

# RandomForest > Arvore de Decisao
from sklearn.ensemble import RandomForestClassifier

# sklearn.metrics para verificar quão acurado são os modelos
from sklearn.metrics import accuracy_score

# Lightgbm
import lightgbm as lgb

# Se for usar o google drive (como vimos em aula)
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<br>

In [ ]:
# Importando base de dados do google drive (ajuste o caminho até seu arquivo)
df = pd.read_csv('drive/MyDrive/clientes.csv', sep=',')

# Descomente, caso queira visualizar a tabela de dados
# df.head(3)

<br>

In [72]:
# Verificando os scores disponíveis
df['score_credito'].unique()

array(['Good', 'Standard', 'Poor'], dtype=object)

<br>

In [73]:
# visualizar formato dos dados
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  object
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  object
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  object
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(7), object(4)
memory usage: 19.1+ MB
None

#

# Pré-Processamento

É Nessa parte que fazemos a limpeza das base e deixamos em um formato que os modelos possam utilizar.

In [74]:
# Vamos usar sklearn.preprocessing para converter as colunas necessárias de text para numbers
# Note: por ser um caso de laboratório a base já esta bem ajustada.

# Escrevi dessa forma, por conta da legibilidade, mas existem muitas opções para reescrever de forma otimizada

labelencoder_profissao = LabelEncoder()
df["profissao"] = labelencoder_profissao.fit_transform(df["profissao"])

labelencoder_mix_credito = LabelEncoder()
df["mix_credito"] = labelencoder_mix_credito.fit_transform(df["mix_credito"])

labelencoder_comportamento_pagamento = LabelEncoder()
df["comportamento_pagamento"] = labelencoder_comportamento_pagamento.fit_transform(df["comportamento_pagamento"])

# Visualizando os formatos dos dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  int64
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  int64
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  int64
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(10), object(1)
memory usage: 19.1+ MB

#

In [75]:
# Em y vamos ter os dados que iremos prever
y = df["score_credito"].copy()

In [76]:
# Em x temos os dados que serão utilizados para treinar o modelo (id_cliente e score_credito podem ser omitidas, uma vez que não usaremos)
columns_model = [
    'mes', 'idade', 'profissao', 'salario_anual', 'num_contas',
    'num_cartoes', 'juros_emprestimo', 'num_emprestimos',
    'dias_atraso', 'num_pagamentos_atrasados', 'num_verificacoes_credito',
    'mix_credito', 'divida_total', 'taxa_uso_credito',
    'idade_historico_credito', 'investimento_mensal',
    'comportamento_pagamento', 'saldo_final_mes',
    'emprestimo_carro', 'emprestimo_casa', 'emprestimo_pessoal',
    'emprestimo_credito', 'emprestimo_estudantil'
]

x = df[columns_model].copy()

In [77]:
# Biblioteca utilizada para separar a base de treino e base de teste
from sklearn.model_selection import train_test_split

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3)

# Vamos testar nossa base com alguns modelos de ML

[Link para biblioteca: Scikit Learn](https://scikit-learn.org/stable/supervised_learning.html)

# Random Forest

In [78]:
# Criação do modelo
modelo_arvoredecisao = RandomForestClassifier()

# Treinamento
modelo_arvoredecisao.fit(x_treino, y_treino)

RandomForestClassifier()

#

# KNN (K-Nearest Neighbors)

In [79]:
# Criação do modelo
modelo_knn = KNeighborsClassifier()

# Treinamento
modelo_knn.fit(x_treino, y_treino)

KNeighborsClassifier()

<br>

# LIGHTGMB

In [80]:
# Criação do modelo (existe uma grande gama de parâmetros que podemos alterar no modelo)
modelo_lightgmb = lgb.LGBMClassifier(n_estimators=200, learning_rate=0.03)

# Treinamento
modelo_lightgmb.fit(x_treino, y_treino)

LGBMClassifier(learning_rate=0.03, n_estimators=200)

<br>

### Vamos utilizar os dados que deixamos reservado para comparar o desempenho.

In [81]:
# verificando as previsões com base nos dados de teste
previsao_arvoredecisao = modelo_arvoredecisao.predict(x_teste)
previsao_knn = modelo_knn.predict(x_teste)
previsao_lightgmb = modelo_lightgmb.predict(x_teste)

In [82]:

print(f'Random Forest ==> {accuracy_score(y_teste, previsao_arvoredecisao)}')
print(f'Nearest Neighbors (KNN) ==> {accuracy_score(y_teste, previsao_knn)}')
print(f'Lightgmb (Lightgmb) ==> {accuracy_score(y_teste, previsao_lightgmb)}')

Random Forest ==> 0.8246
Nearest Neighbors (KNN) ==> 0.7380666666666666
Lightgmb (Lightgmb) ==> 0.7234

<br>

Verificamos que pra esse problema o modelo de arvore de decisão teve o melhor desempenho. Poderíamos fazer várias modificações ou testar outros para tentar ter mais performance.

Agora podemos usar o melhor modelo para classificar novos clientes

In [ ]:
# novos_clientes (ajuste o caminho até seu arquivo)
df_novos_clientes = pd.read_csv("drive/MyDrive/clientesNovos.csv", sep=',')

# Pré processamento (igual fizemos com a base de treino)
df_novos_clientes["profissao"] = labelencoder_profissao.transform(df_novos_clientes["profissao"])
df_novos_clientes["mix_credito"] = labelencoder_mix_credito.transform(df_novos_clientes["mix_credito"])
df_novos_clientes["comportamento_pagamento"] = labelencoder_comportamento_pagamento.transform(df_novos_clientes["comportamento_pagamento"])

# Descomente, caso queira visualizar a tabela de novos clientes
df_novos_clientes

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,taxa_uso_credito,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,1,31.0,5,19300.340,6.0,7.0,17.0,5.0,52.0,19.0,...,29.934186,218.0,44.50951,4,312.487689,1,1,0,0,0
1,4,32.0,0,12600.445,5.0,5.0,10.0,3.0,25.0,18.0,...,28.819407,12.0,0.00000,5,300.994163,0,0,0,0,1
2,2,48.0,5,20787.690,8.0,6.0,14.0,7.0,24.0,14.0,...,34.235853,215.0,0.00000,3,345.081577,0,1,0,1,0

In [84]:
# Calculando os score de crédito com base no modelo KNN
score_previsao = modelo_arvoredecisao.predict(df_novos_clientes)
print(score_previsao)

['Poor' 'Poor' 'Standard']

In [85]:
# Adicionando a coluna com os scores para os novos clientes
df_novos_clientes['score_credito'] = score_previsao

df_novos_clientes

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil,score_credito
0,1,31.0,5,19300.340,6.0,7.0,17.0,5.0,52.0,19.0,...,218.0,44.50951,4,312.487689,1,1,0,0,0,Poor
1,4,32.0,0,12600.445,5.0,5.0,10.0,3.0,25.0,18.0,...,12.0,0.00000,5,300.994163,0,0,0,0,1,Poor
2,2,48.0,5,20787.690,8.0,6.0,14.0,7.0,24.0,14.0,...,215.0,0.00000,3,345.081577,0,1,0,1,0,Standard

Esse script foi adaptado de https://www.kaggle.com/